<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>Browy</RootNamespace>
    <AssemblyName>Browy</AssemblyName>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Web.WebView2.Core">
      <HintPath>C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\PrivateAssemblies\Microsoft.Web.WebView2.Core.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.Wpf">
      <HintPath>C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\PrivateAssemblies\Microsoft.Web.WebView2.Wpf.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\PrivateAssemblies\WebView2Loader.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\PrivateAssemblies\WebView2Loader.dll" Link="runtimes\win-x64\native\WebView2Loader.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
